"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emailService = void 0;

/**
 * Single outbound-mail path for the whole app (password-reset OTPs, welcome
 * mail, payslips, and leave-request approver alerts alike), backed by
 * Brevo's transactional email HTTP API rather than raw SMTP.
 *
 * This used to go through nodemailer over SMTP (smtp-relay.brevo.com:587),
 * but on Railway that connection was timing out — the request logs showed
 * "[email:leave] send failed: Connection timeout" every time a leave
 * request tried to notify its approvers, which means the container's
 * outbound network never completed the TCP handshake to port 587 at all
 * (an auth or TLS problem fails in milliseconds; this just hung until
 * nodemailer gave up). Railway's network is known to be unreliable for
 * exactly this — direct SMTP ports (25/465/587) get silently dropped in
 * some regions/plans — so the fix is to stop using SMTP entirely and call
 * Brevo's REST API over plain HTTPS (port 443) instead, which is never
 * blocked. Reads BREVO_API_KEY (the API key from Brevo's SMTP & API page —
 * NOT the SMTP key used before) and LEAVE_EMAIL_FROM (unchanged, still the
 * verified sender). The old LEAVE_SMTP_HOST/LEAVE_SMTP_PORT/
 * LEAVE_SMTP_SECURE/LEAVE_SMTP_USER/LEAVE_SMTP_PASSWORD variables are no
 * longer read anywhere and can be left in Railway or removed at your
 * convenience.
 */
const BREVO_API_URL = 'https://api.brevo.com/v3/smtp/email';
const BREVO_API_KEY = process.env.BREVO_API_KEY;
const SMTP_CONFIGURED = Boolean(BREVO_API_KEY);

/** Splits a "Name <email>" string (or a bare email) into Brevo's {name, email} sender shape. */
function parseFrom(raw) {
    const fallback = { name: 'DutyLaunch HRMS', email: 'noreply@dutylaunch.com' };
    if (!raw)
        return fallback;
    const match = raw.match(/^\s*"?([^"<]*)"?\s*<([^>]+)>\s*$/);
    if (match) {
        const name = match[1].trim();
        return { name: name || fallback.name, email: match[2].trim() };
    }
    return { name: fallback.name, email: raw.trim() };
}
const MAIL_FROM = parseFrom(process.env.LEAVE_EMAIL_FROM);

/**
 * Sends a mail via Brevo's HTTP API, or logs and resolves when it's not
 * configured. Outbound mail is a convenience here — a missing setup or a
 * delivery failure must never fail the request that triggered it.
 */
async function send({ to, subject, html }) {
    if (!SMTP_CONFIGURED) {
        console.warn(`[email] BREVO_API_KEY is not configured — skipped "${subject}" to ${to}`);
        return { skipped: true };
    }
    try {
        const res = await fetch(BREVO_API_URL, {
            method: 'POST',
            headers: {
                accept: 'application/json',
                'content-type': 'application/json',
                'api-key': BREVO_API_KEY,
            },
            body: JSON.stringify({
                sender: MAIL_FROM,
                to: [{ email: to }],
                subject,
                htmlContent: html,
            }),
        });
        if (!res.ok) {
            const body = await res.text().catch(() => '');
            throw new Error(`Brevo API responded ${res.status}: ${body}`);
        }
        const result = await res.json();
        // A success here previously left no trace in the logs at all, which
        // made it impossible to tell "this was never attempted" apart from
        // "this was sent" when something downstream wasn't showing up.
        console.log(`[email] sent "${subject}" to ${to} (messageId: ${result?.messageId || 'n/a'})`);
        return result;
    }
    catch (err) {
        console.error('[email] send failed:', err.message);
        return { failed: true, error: err.message };
    }
}

exports.emailService = {
    /**
     * Emails the 6-digit numeric OTP generated by authController.forgotPassword.
     * The code itself is never stored anywhere (the DB only keeps a hash of
     * it), so this email is the only place the requesting user can read it
     * from — it always goes to the account's own address, never anyone else's.
     */
    async sendPasswordResetOtp(email, otp, name) {
        await send({
            to: email,
            subject: 'Your password reset code - DutyLaunch HRMS',
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${name},</p>
          <p>Use the code below to reset your password. It expires in 10 minutes.</p>
          <div style="display: inline-block; padding: 16px 28px; background: #eef2ff; color: #1e40af; font-size: 28px; font-weight: bold; letter-spacing: 8px; border-radius: 6px; margin: 16px 0;">${otp}</div>
          <p>If you did not request this, please ignore this email — your password will not change.</p>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
    async sendWelcome(email, name, tempPassword) {
        await send({
            to: email,
            subject: 'Welcome to DutyLaunch HRMS',
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">Welcome to DutyLaunch HRMS</h2>
          <p>Hi ${name},</p>
          <p>Your account has been created. Please use the following credentials:</p>
          <p><strong>Email:</strong> ${email}</p>
          <p><strong>Temporary Password:</strong> ${tempPassword}</p>
          <p>Please change your password after first login.</p>
          <a href="${process.env.CLIENT_URL}/login" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">Login Now</a>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
    /**
     * Called from payrollController.buildPayslip right after a payslip is
     * generated (single or bulk) — always to that one employee's own account
     * email, looked up the same way as everywhere else in this file, never
     * to HR/finance/whoever triggered the generation.
     */
    async sendPayslip(email, name, month, year) {
        await send({
            to: email,
            subject: `Payslip for ${month} ${year} - DutyLaunch HRMS`,
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${name},</p>
          <p>Your payslip for ${month} ${year} has been generated. Please login to the portal to view and download it.</p>
          <a href="${process.env.CLIENT_URL}/portal/payslips" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">View Payslip</a>
        </div>
      `,
        });
    },
    /**
     * Tells the employee who filed a leave request that it's been approved
     * or rejected. Called from leaveController.approveLeave/rejectLeave
     * right after the decision is saved, always to that employee's own
     * account email (see leaveController's emailRequesterOfDecision) —
     * never anyone else's.
     */
    async sendLeaveDecision(email, employeeName, details) {
        const { status, leaveType, subType, startDate, endDate, totalDays, note } = details;
        const dateRange = startDate === endDate ? startDate : `${startDate} to ${endDate}`;
        const approved = status === 'APPROVED';
        const reviewUrl = `${process.env.CLIENT_URL}/leave`;
        await send({
            to: email,
            subject: `Your leave request was ${approved ? 'approved' : 'rejected'} - DutyLaunch HRMS`,
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${employeeName},</p>
          <p>Your leave request has been <strong style="color: ${approved ? '#16a34a' : '#dc2626'};">${approved ? 'approved' : 'rejected'}</strong>.</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr><td style="padding: 6px 0; color: #6b7280;">Leave type</td><td style="padding: 6px 0;"><strong>${leaveType}${subType ? ` (${subType})` : ''}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Dates</td><td style="padding: 6px 0;"><strong>${dateRange}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Duration</td><td style="padding: 6px 0;"><strong>${totalDays} day(s)</strong></td></tr>
            ${note ? `<tr><td style="padding: 6px 0; color: #6b7280; vertical-align: top;">${approved ? 'Note' : 'Reason'}</td><td style="padding: 6px 0;">${note}</td></tr>` : ''}
          </table>
          <a href="${reviewUrl}" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">View in HRMS</a>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
    /**
     * Notifies one platform administrator (CTO / CEO / Super Admin — see
     * utils/roles.js COMPENSATION_APPROVER_ROLES) that an employee's proposed
     * compensation change needs their decision. Called once per recipient
     * from compensationController.createRequest right after the request is
     * saved; a delivery failure is swallowed by send() above and never
     * blocks the request from being filed.
     */
    async sendCompensationRequestAlert(email, recipientName, details) {
        const { employeeName, employeeCode, currentGross, proposedGross, changeAmount, reason } = details;
        const direction = proposedGross >= currentGross ? 'increase' : 'decrease';
        const reviewUrl = `${process.env.CLIENT_URL}/payroll`;
        await send({
            to: email,
            subject: `Compensation change request from ${employeeName} — action needed`,
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${recipientName},</p>
          <p>A compensation change has been proposed for <strong>${employeeName}</strong>${employeeCode ? ` (${employeeCode})` : ''} and is awaiting your decision.</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr><td style="padding: 6px 0; color: #6b7280;">Current gross</td><td style="padding: 6px 0;"><strong>₹${currentGross}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Proposed gross</td><td style="padding: 6px 0;"><strong>₹${proposedGross}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Change</td><td style="padding: 6px 0;"><strong>${direction} of ₹${Math.abs(changeAmount)}</strong></td></tr>
            ${reason ? `<tr><td style="padding: 6px 0; color: #6b7280; vertical-align: top;">Reason</td><td style="padding: 6px 0;">${reason}</td></tr>` : ''}
          </table>
          <a href="${reviewUrl}" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">Review request</a>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
    /**
     * Tells whoever has a stake in a compensation decision — the affected
     * employee, and separately the HR admin who filed the request on their
     * behalf — that it's been approved or rejected. Called from
     * compensationController's emailCompensationDecision right after the
     * decision is saved, once per recipient, each to that person's own
     * account email (never anyone else's — see emailCompensationDecision).
     */
    async sendCompensationDecision(email, recipientName, details) {
        const { status, employeeName, currentGross, proposedGross, note, forRequester } = details;
        const approved = status === 'APPROVED';
        const reviewUrl = `${process.env.CLIENT_URL}/payroll`;
        const headline = forRequester
            ? `The compensation change you requested for <strong>${employeeName}</strong> has been <strong style="color: ${approved ? '#16a34a' : '#dc2626'};">${approved ? 'approved' : 'rejected'}</strong>.`
            : `A proposed change to your compensation has been <strong style="color: ${approved ? '#16a34a' : '#dc2626'};">${approved ? 'approved' : 'rejected'}</strong>.`;
        await send({
            to: email,
            subject: `Compensation change ${approved ? 'approved' : 'rejected'} - DutyLaunch HRMS`,
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${recipientName},</p>
          <p>${headline}</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr><td style="padding: 6px 0; color: #6b7280;">Current gross</td><td style="padding: 6px 0;"><strong>₹${currentGross}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Proposed gross</td><td style="padding: 6px 0;"><strong>₹${proposedGross}</strong></td></tr>
            ${note ? `<tr><td style="padding: 6px 0; color: #6b7280; vertical-align: top;">${approved ? 'Note' : 'Reason'}</td><td style="padding: 6px 0;">${note}</td></tr>` : ''}
          </table>
          <a href="${reviewUrl}" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">View in HRMS</a>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
    /**
     * Notifies one approver (CTO / CEO / Project Head — see
     * utils/roles.js LEAVE_EMAIL_NOTIFY_ROLES) that a new leave request needs
     * review. Called once per recipient from leaveController.createLeaveRequest
     * right after the request is saved; a delivery failure is swallowed by
     * send() above and never blocks the employee's request from succeeding.
     */
    async sendLeaveRequestAlert(email, recipientName, details) {
        const {
            employeeName, employeeCode, department, leaveType, subType,
            startDate, endDate, totalDays, reason,
        } = details;
        const dateRange = startDate === endDate ? startDate : `${startDate} to ${endDate}`;
        const reviewUrl = `${process.env.CLIENT_URL}/leave`;
        await send({
            to: email,
            subject: `New leave request from ${employeeName} — action needed`,
            html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1e40af;">DutyLaunch HRMS</h2>
          <p>Hi ${recipientName},</p>
          <p><strong>${employeeName}</strong>${employeeCode ? ` (${employeeCode})` : ''}${department ? ` from ${department}` : ''} has requested leave and it is awaiting review.</p>
          <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
            <tr><td style="padding: 6px 0; color: #6b7280;">Leave type</td><td style="padding: 6px 0;"><strong>${leaveType}${subType ? ` (${subType})` : ''}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Dates</td><td style="padding: 6px 0;"><strong>${dateRange}</strong></td></tr>
            <tr><td style="padding: 6px 0; color: #6b7280;">Duration</td><td style="padding: 6px 0;"><strong>${totalDays} day(s)</strong></td></tr>
            ${reason ? `<tr><td style="padding: 6px 0; color: #6b7280; vertical-align: top;">Reason</td><td style="padding: 6px 0;">${reason}</td></tr>` : ''}
          </table>
          <a href="${reviewUrl}" style="display: inline-block; padding: 12px 24px; background: #1e40af; color: white; text-decoration: none; border-radius: 4px;">Review request</a>
          <hr/>
          <small style="color: #6b7280;">DutyLaunch Solutions Private Limited</small>
        </div>
      `,
        });
    },
};
//# sourceMappingURL=emailService.js.map