"use strict";
/**
 * Seeds the DutyLaunch HRMS demo database.
 *
 * The script clears every collection it owns before writing, so running it twice
 * refreshes the dataset instead of duplicating it. All references are created from
 * documents saved earlier in the same run, so there are never dangling ObjectIds.
 *
 *   npm run seed
 */
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
require("dotenv/config");
const mongoose_1 = __importDefault(require("mongoose"));
const bcryptjs_1 = __importDefault(require("bcryptjs"));
const path_1 = __importDefault(require("path"));
const fs_1 = __importDefault(require("fs"));
const PDFDocument = require("pdfkit");

const { User } = require("../models/User");
const { Employee } = require("../models/Employee");
const { LeaveType, LeaveBalance, LeaveRequest, Holiday } = require("../models/Leave");
const { Attendance } = require("../models/Attendance");
const { SalaryStructure, Payslip, CompensationRequest } = require("../models/Payroll");
const { EmployeeDocument, IdentityDocument } = require("../models/Document");
const { Policy, PolicyAcknowledgement, Announcement, AnnouncementRead } = require("../models/PolicyAnnouncement");
const { Asset, AssetAssignment, OnboardingTask, OffboardingTask } = require("../models/AssetOnboarding");
const { Notification, AuditLog } = require("../models/NotificationAudit");
const { TEMPLATES } = require("../controllers/taskController");
const { encrypt, maskIdentityNumber } = require("../utils/encryption");
const { REQUIRED_DOCUMENT_TYPES, buildChecklist, hasRejectedRequiredDocument } = require("../utils/documentRequirements");
const data = require("./data");

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/dutylaunch-hrms';
const ADMIN_PASSWORD = process.env.SEED_ADMIN_PASSWORD || 'Admin@123456';
const EMPLOYEE_PASSWORD = process.env.SEED_EMPLOYEE_PASSWORD || 'Employee@123456';
const UPLOAD_DIR = process.env.UPLOAD_DIR || 'uploads';

const NOW = new Date();
const YEAR = NOW.getFullYear();

// ---------------------------------------------------------------------------
// Small deterministic helpers — a fixed seed keeps re-runs reproducible.
// ---------------------------------------------------------------------------
let rngState = 20260829;
function rnd() {
    rngState = (rngState * 1103515245 + 12345) % 2147483648;
    return rngState / 2147483648;
}
function pick(list) { return list[Math.floor(rnd() * list.length)]; }
function chance(p) { return rnd() < p; }
function intBetween(min, max) { return min + Math.floor(rnd() * (max - min + 1)); }
function addDays(date, days) { return new Date(new Date(date).getTime() + days * 86400000); }
function atTime(date, hours, minutes) {
    const d = new Date(date);
    d.setHours(hours, minutes, 0, 0);
    return d;
}
function startOfDay(date) {
    const d = new Date(date);
    d.setHours(0, 0, 0, 0);
    return d;
}
function isWeekend(date) {
    const day = new Date(date).getDay();
    return day === 0 || day === 6;
}

const testAccounts = [
    { email: 'admin@launcherdesk.com', role: 'SUPER_ADMIN' },
    { email: 'hr@launcherdesk.com', role: 'HR_ADMIN' },
    { email: 'finance@launcherdesk.com', role: 'FINANCE' },
    { email: 'auditor@launcherdesk.com', role: 'AUDITOR' },
];

/** Writes a small real PDF so seeded documents can actually be downloaded. */
function writePdf(absolutePath, title, lines) {
    return new Promise((resolve, reject) => {
        fs_1.default.mkdirSync(path_1.default.dirname(absolutePath), { recursive: true });
        const doc = new PDFDocument({ margin: 50 });
        const stream = fs_1.default.createWriteStream(absolutePath);
        doc.pipe(stream);
        doc.fontSize(18).fillColor('#4338ca').text('DutyLaunch Solutions Private Limited', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(14).fillColor('#111827').text(title, { align: 'center' });
        doc.moveDown(1);
        doc.fontSize(11).fillColor('#374151');
        lines.forEach((line) => { doc.text(line); doc.moveDown(0.3); });
        doc.moveDown(2);
        doc.fontSize(9).fillColor('#6b7280').text('Sample document generated by the HRMS seeder for demonstration purposes.', { align: 'center' });
        doc.end();
        stream.on('finish', () => resolve(fs_1.default.statSync(absolutePath).size));
        stream.on('error', reject);
    });
}

async function clearCollections() {
    await Promise.all([
        User.deleteMany({}), Employee.deleteMany({}),
        LeaveType.deleteMany({}), LeaveBalance.deleteMany({}), LeaveRequest.deleteMany({}), Holiday.deleteMany({}),
        Attendance.deleteMany({}),
        SalaryStructure.deleteMany({}), Payslip.deleteMany({}), CompensationRequest.deleteMany({}),
        EmployeeDocument.deleteMany({}), IdentityDocument.deleteMany({}),
        Policy.deleteMany({}), PolicyAcknowledgement.deleteMany({}),
        Announcement.deleteMany({}), AnnouncementRead.deleteMany({}),
        Asset.deleteMany({}), AssetAssignment.deleteMany({}),
        OnboardingTask.deleteMany({}), OffboardingTask.deleteMany({}),
        Notification.deleteMany({}),
        // AuditLog blocks updateOne/deleteOne, but deleteMany is allowed and is what a
        // full reseed needs. In production the collection stays append-only.
        AuditLog.deleteMany({}),
    ]);
}

async function seed() {
    await mongoose_1.default.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    await clearCollections();
    console.log('🗑️  Cleared existing data');

    // -----------------------------------------------------------------------
    // Leave types & holidays
    // -----------------------------------------------------------------------
    const savedLeaveTypes = await LeaveType.insertMany(data.leaveTypes.map((t) => ({ ...t, isActive: true })));
    const leaveTypeByCode = Object.fromEntries(savedLeaveTypes.map((t) => [t.code, t]));
    console.log(`✅ ${savedLeaveTypes.length} leave types`);

    await Holiday.insertMany(data.holidays.map((h) => ({
        name: h.name,
        date: new Date(YEAR, h.month - 1, h.day),
        type: h.type,
        year: YEAR,
        isActive: true,
    })));
    console.log(`✅ ${data.holidays.length} holidays for ${YEAR}`);

    // -----------------------------------------------------------------------
    // Standalone role accounts (not linked to an employee record)
    // -----------------------------------------------------------------------
    const adminHash = await bcryptjs_1.default.hash(ADMIN_PASSWORD, 12);
    const roleUsers = await User.insertMany(testAccounts.map((a) => ({
        email: a.email, password: adminHash, role: a.role, isActive: true,
    })));
    const superAdmin = roleUsers.find((u) => u.role === 'SUPER_ADMIN');
    console.log(`✅ ${roleUsers.length} role accounts`);

    // -----------------------------------------------------------------------
    // Employees + their logins
    // -----------------------------------------------------------------------
    const employeeHash = await bcryptjs_1.default.hash(EMPLOYEE_PASSWORD, 12);
    const allEmployeeSpecs = [
        ...data.foundingEmployees,
        ...data.demoEmployees.map((e) => ({ ...e, role: e.role || 'EMPLOYEE', status: e.status || 'ACTIVE', employmentType: e.employmentType || 'FULL_TIME' })),
    ];

    const byCode = {};
    for (const spec of allEmployeeSpecs) {
        const fullName = `${spec.firstName}${spec.lastName ? ` ${spec.lastName}` : ''}`.trim();
        const isActive = spec.status !== 'INACTIVE';
        const employee = await Employee.create({
            employeeCode: spec.employeeCode,
            firstName: spec.firstName,
            lastName: spec.lastName || '',
            fullName,
            officialEmail: spec.officialEmail || `${spec.firstName.split(' ')[0].toLowerCase()}.${(spec.lastName || spec.employeeCode).split(' ')[0].toLowerCase()}@launcherdesk.com`,
            personalEmail: `${spec.firstName.split(' ')[0].toLowerCase()}.${spec.employeeCode.toLowerCase()}@gmail.com`,
            personalMobile: `+91 9${intBetween(100000000, 899999999)}`,
            designation: spec.designation,
            department: spec.department,
            employmentType: spec.employmentType || 'FULL_TIME',
            status: spec.status || 'ACTIVE',
            dateOfJoining: new Date(spec.dateOfJoining),
            dateOfExit: spec.dateOfExit ? new Date(spec.dateOfExit) : undefined,
            exitReason: spec.exitReason,
            noticePeriodDays: spec.noticePeriodDays,
            probationEndDate: spec.status === 'PROBATION' ? addDays(spec.dateOfJoining, 180) : undefined,
            confirmationDate: spec.status === 'ACTIVE' ? addDays(spec.dateOfJoining, 180) : undefined,
            dateOfBirth: spec.dateOfBirth ? new Date(spec.dateOfBirth) : undefined,
            gender: spec.gender,
            bloodGroup: pick(['A+', 'B+', 'O+', 'AB+', 'A-', 'O-']),
            nationality: 'Indian',
            workLocation: spec.workLocation || pick(['Bengaluru HQ', 'Bengaluru HQ', 'Hyderabad Office', 'Remote']),
            isArchived: false,
        });
        const user = await User.create({
            email: employee.officialEmail,
            password: isActive ? employeeHash : await bcryptjs_1.default.hash(`${spec.employeeCode}@Duty!`, 12),
            role: spec.role,
            isActive,
            employee: employee._id,
        });
        employee.user = user._id;
        await employee.save();
        byCode[spec.employeeCode] = employee;
    }

    // Reporting lines are set in a second pass, once every employee exists.
    for (const spec of data.demoEmployees) {
        if (spec.managerCode && byCode[spec.managerCode]) {
            byCode[spec.employeeCode].manager = byCode[spec.managerCode]._id;
            await byCode[spec.employeeCode].save();
        }
    }
    const employees = Object.values(byCode);
    const activeEmployees = employees.filter((e) => e.status !== 'INACTIVE');
    console.log(`✅ ${employees.length} employees (${activeEmployees.length} active)`);

    // -----------------------------------------------------------------------
    // Attendance — the last 45 calendar days, weekdays only
    // -----------------------------------------------------------------------
    const attendanceRows = [];
    for (const employee of activeEmployees) {
        for (let back = 45; back >= 0; back -= 1) {
            const day = startOfDay(addDays(NOW, -back));
            if (isWeekend(day)) continue;
            if (day < startOfDay(employee.dateOfJoining)) continue;
            if (employee.dateOfExit && day > startOfDay(employee.dateOfExit)) continue;

            const roll = rnd();
            let status;
            let checkIn;
            let checkOut;
            if (roll < 0.80) {
                status = 'PRESENT';
                checkIn = atTime(day, 9, intBetween(5, 29));
                checkOut = atTime(day, 18, intBetween(30, 59));
            } else if (roll < 0.89) {
                status = 'LATE';
                checkIn = atTime(day, 10, intBetween(0, 55));
                checkOut = atTime(day, 19, intBetween(0, 40));
            } else if (roll < 0.94) {
                status = 'WORK_FROM_HOME';
                checkIn = atTime(day, 9, intBetween(0, 40));
                checkOut = atTime(day, 18, intBetween(15, 55));
            } else if (roll < 0.965) {
                status = 'HALF_DAY';
                checkIn = atTime(day, 9, intBetween(10, 30));
                checkOut = atTime(day, 13, intBetween(30, 59));
            } else if (roll < 0.985) {
                status = 'ON_LEAVE';
            } else {
                status = 'ABSENT';
            }

            const shiftStart = atTime(day, 9, 30);
            const shiftEnd = atTime(day, 18, 30);
            attendanceRows.push({
                employee: employee._id,
                date: day,
                checkIn,
                checkOut,
                status,
                workHours: checkIn && checkOut ? Math.round(((checkOut - checkIn) / 3600000) * 100) / 100 : undefined,
                isLate: Boolean(checkIn && checkIn > shiftStart),
                lateMinutes: checkIn && checkIn > shiftStart ? Math.floor((checkIn - shiftStart) / 60000) : 0,
                isEarlyExit: Boolean(checkOut && checkOut < shiftEnd),
                earlyExitMinutes: checkOut && checkOut < shiftEnd ? Math.floor((shiftEnd - checkOut) / 60000) : 0,
                notes: status === 'ABSENT' ? 'No check-in recorded' : undefined,
            });
        }
    }
    await Attendance.insertMany(attendanceRows);
    console.log(`✅ ${attendanceRows.length} attendance records`);

    // -----------------------------------------------------------------------
    // Leave requests + balances
    // -----------------------------------------------------------------------
    const leaveRequests = [];
    const typeCodes = ['CL', 'SL', 'EL', 'CO', 'UL'];
    for (const employee of activeEmployees) {
        const requestCount = intBetween(1, 4);
        for (let i = 0; i < requestCount; i += 1) {
            const type = leaveTypeByCode[pick(typeCodes)];
            const startOffset = intBetween(-140, 40);
            const start = startOfDay(addDays(NOW, startOffset));
            if (start < startOfDay(employee.dateOfJoining)) continue;
            const length = chance(0.45) ? 1 : intBetween(2, 4);
            const end = addDays(start, length - 1);

            // Future-dated requests stay pending; past ones are already decided.
            let status;
            if (start > NOW) status = chance(0.6) ? 'PENDING' : 'APPROVED';
            else if (chance(0.72)) status = 'APPROVED';
            else if (chance(0.6)) status = 'REJECTED';
            else status = 'CANCELLED';

            leaveRequests.push({
                employee: employee._id,
                leaveType: type._id,
                startDate: start,
                endDate: end,
                totalDays: length,
                isHalfDay: false,
                reason: pick(data.leaveReasons),
                status,
                approvedBy: status === 'APPROVED' ? superAdmin._id : undefined,
                approvedAt: status === 'APPROVED' ? addDays(start, -2) : undefined,
                rejectedBy: status === 'REJECTED' ? superAdmin._id : undefined,
                rejectedAt: status === 'REJECTED' ? addDays(start, -2) : undefined,
                rejectionReason: status === 'REJECTED' ? 'Team capacity is already stretched for these dates.' : undefined,
                createdAt: addDays(start, -5),
            });
        }
    }
    // Non-overlapping guarantee: keep only the first request per employee/date span.
    const accepted = [];
    const spans = new Map();
    for (const req of leaveRequests) {
        if (!['PENDING', 'APPROVED'].includes(req.status)) { accepted.push(req); continue; }
        const key = String(req.employee);
        const existing = spans.get(key) || [];
        const clashes = existing.some((s) => req.startDate <= s.end && req.endDate >= s.start);
        if (clashes) continue;
        existing.push({ start: req.startDate, end: req.endDate });
        spans.set(key, existing);
        accepted.push(req);
    }
    await LeaveRequest.insertMany(accepted);
    console.log(`✅ ${accepted.length} leave requests`);

    // Balances are derived from the requests, exactly as the API recomputes them.
    const balanceRows = [];
    for (const employee of activeEmployees) {
        for (const type of savedLeaveTypes) {
            const own = accepted.filter((r) => String(r.employee) === String(employee._id)
                && String(r.leaveType) === String(type._id)
                && new Date(r.startDate).getFullYear() === YEAR);
            const usedDays = own.filter((r) => r.status === 'APPROVED').reduce((s, r) => s + r.totalDays, 0);
            const pendingDays = own.filter((r) => r.status === 'PENDING').reduce((s, r) => s + r.totalDays, 0);
            balanceRows.push({
                employee: employee._id,
                leaveType: type._id,
                year: YEAR,
                totalDays: type.maxDaysPerYear,
                usedDays,
                pendingDays,
                remainingDays: Math.max(0, type.maxDaysPerYear - usedDays - pendingDays),
            });
        }
    }
    await LeaveBalance.insertMany(balanceRows);
    console.log(`✅ ${balanceRows.length} leave balances`);

    // -----------------------------------------------------------------------
    // Salary structures + payslips for the last three months
    // -----------------------------------------------------------------------
    const structures = [];
    for (const employee of activeEmployees) {
        const spec = data.demoEmployees.find((d) => d.employeeCode === employee.employeeCode);
        const basic = spec?.basic || intBetween(45, 120) * 1000;
        const hra = Math.round(basic * 0.4);
        const da = Math.round(basic * 0.1);
        const specialAllowance = Math.round(basic * 0.15);
        const otherAllowances = 2500;
        const gross = basic + hra + da + specialAllowance + otherAllowances;
        const pf = Math.min(1800, Math.round(basic * 0.12));
        const esi = gross <= 21000 ? Math.round(gross * 0.0075) : 0;
        const tds = gross > 60000 ? Math.round(gross * 0.08) : 0;
        const otherDeductions = 200;
        const totalDeductions = pf + esi + tds + otherDeductions;
        structures.push({
            employee: employee._id,
            effectiveFrom: employee.dateOfJoining,
            basic, hra, da, specialAllowance, otherAllowances,
            pf, esi, tds, otherDeductions,
            grossSalary: gross,
            netSalary: gross - totalDeductions,
            isActive: true,
            createdBy: superAdmin._id,
        });
    }
    const savedStructures = await SalaryStructure.insertMany(structures);
    console.log(`✅ ${savedStructures.length} salary structures`);

    // -----------------------------------------------------------------------
    // Compensation change requests — demonstrates the HR-requests /
    // SUPER_ADMIN-or-CTO-approves workflow in every status.
    // -----------------------------------------------------------------------
    const hrUser = roleUsers.find((u) => u.role === 'HR_ADMIN');
    const compensationCandidates = savedStructures.slice(0, 3);
    const compensationRows = [];
    if (compensationCandidates[0]) {
        const s = compensationCandidates[0];
        const proposedBasic = Math.round(s.basic * 1.1);
        compensationRows.push({
            employee: s.employee,
            currentBasic: s.basic, currentHra: s.hra, currentDa: s.da,
            currentSpecialAllowance: s.specialAllowance, currentOtherAllowances: s.otherAllowances,
            currentGross: s.grossSalary,
            proposedBasic, proposedHra: s.hra, proposedDa: s.da,
            proposedSpecialAllowance: s.specialAllowance, proposedOtherAllowances: s.otherAllowances,
            proposedGross: proposedBasic + s.hra + s.da + s.specialAllowance + s.otherAllowances,
            changeAmount: proposedBasic - s.basic,
            changePercent: Math.round(((proposedBasic - s.basic) / s.grossSalary) * 10000) / 100,
            reason: 'Annual performance increment recommendation.',
            status: 'PENDING',
            requestedBy: hrUser._id,
        });
    }
    if (compensationCandidates[1]) {
        const s = compensationCandidates[1];
        const proposedSpecialAllowance = Math.round(s.specialAllowance * 1.15);
        const proposedGross = s.basic + s.hra + s.da + proposedSpecialAllowance + s.otherAllowances;
        compensationRows.push({
            employee: s.employee,
            currentBasic: s.basic, currentHra: s.hra, currentDa: s.da,
            currentSpecialAllowance: s.specialAllowance, currentOtherAllowances: s.otherAllowances,
            currentGross: s.grossSalary,
            proposedBasic: s.basic, proposedHra: s.hra, proposedDa: s.da,
            proposedSpecialAllowance, proposedOtherAllowances: s.otherAllowances,
            proposedGross,
            changeAmount: proposedGross - s.grossSalary,
            changePercent: Math.round(((proposedGross - s.grossSalary) / s.grossSalary) * 10000) / 100,
            reason: 'Retention adjustment following a competing offer.',
            status: 'APPROVED',
            requestedBy: hrUser._id,
            reviewedBy: superAdmin._id,
            reviewedAt: addDays(NOW, -5),
            reviewComments: 'Approved — within budget for this quarter.',
        });
    }
    if (compensationCandidates[2]) {
        const s = compensationCandidates[2];
        const proposedBasic = Math.round(s.basic * 1.25);
        compensationRows.push({
            employee: s.employee,
            currentBasic: s.basic, currentHra: s.hra, currentDa: s.da,
            currentSpecialAllowance: s.specialAllowance, currentOtherAllowances: s.otherAllowances,
            currentGross: s.grossSalary,
            proposedBasic, proposedHra: s.hra, proposedDa: s.da,
            proposedSpecialAllowance: s.specialAllowance, proposedOtherAllowances: s.otherAllowances,
            proposedGross: proposedBasic + s.hra + s.da + s.specialAllowance + s.otherAllowances,
            changeAmount: proposedBasic - s.basic,
            changePercent: Math.round(((proposedBasic - s.basic) / s.grossSalary) * 10000) / 100,
            reason: 'Requested market-correction increase.',
            status: 'REJECTED',
            requestedBy: hrUser._id,
            reviewedBy: superAdmin._id,
            reviewedAt: addDays(NOW, -3),
            reviewComments: 'Increase exceeds the department budget for this cycle — revisit next review.',
        });
    }
    const savedCompensationRequests = await CompensationRequest.insertMany(compensationRows);
    console.log(`✅ ${compensationRows.length} compensation change requests`);

    const payslipRows = [];
    for (const structure of savedStructures) {
        for (let back = 1; back <= 3; back += 1) {
            const period = new Date(YEAR, NOW.getMonth() - back, 1);
            const month = period.getMonth() + 1;
            const year = period.getFullYear();
            const employee = employees.find((e) => String(e._id) === String(structure.employee));
            if (period < new Date(employee.dateOfJoining.getFullYear(), employee.dateOfJoining.getMonth(), 1)) continue;
            const periodEnd = new Date(year, month, 0);
            const totalEarnings = structure.basic + structure.hra + structure.da + structure.specialAllowance + structure.otherAllowances;
            const totalDeductions = structure.pf + structure.esi + structure.tds + structure.otherDeductions;
            payslipRows.push({
                employee: structure.employee,
                salaryStructure: structure._id,
                month, year,
                payPeriodStart: new Date(year, month - 1, 1),
                payPeriodEnd: periodEnd,
                basic: structure.basic, hra: structure.hra, da: structure.da,
                specialAllowance: structure.specialAllowance, otherAllowances: structure.otherAllowances,
                totalEarnings,
                pf: structure.pf, esi: structure.esi, tds: structure.tds, otherDeductions: structure.otherDeductions,
                totalDeductions,
                grossSalary: totalEarnings,
                netSalary: totalEarnings - totalDeductions,
                workingDays: periodEnd.getDate(),
                paidDays: periodEnd.getDate(),
                lop: 0,
                // The two older months are settled; the most recent one is still generated.
                status: back === 1 ? 'GENERATED' : 'PAID',
                paidOn: back === 1 ? undefined : new Date(year, month, 1),
                generatedBy: superAdmin._id,
            });
        }
    }
    await Payslip.insertMany(payslipRows);
    console.log(`✅ ${payslipRows.length} payslips`);

    // -----------------------------------------------------------------------
    // Documents — real PDFs on disk so download/verify genuinely work
    // -----------------------------------------------------------------------
    const documentRows = [];
    const documentEmployees = activeEmployees.slice(0, 18);
    // Required categories per utils/documentRequirements.js — kept in one
    // place so the seed and the live checklist can never disagree.
    const requiredCategories = REQUIRED_DOCUMENT_TYPES.filter((t) => t.required).map((t) => t.category);
    const catalogueByCategory = Object.fromEntries(data.documentCatalogue.map((c) => [c.category, c]));

    async function seedDocument(employee, entry, status) {
        const relativePath = `documents/${employee._id}/${entry.category.replace(/\W+/g, '-').toLowerCase()}.pdf`;
        const absolutePath = path_1.default.join(UPLOAD_DIR, relativePath);
        const size = await writePdf(absolutePath, entry.name, [
            `Employee: ${employee.fullName} (${employee.employeeCode})`,
            `Department: ${employee.department}`,
            `Designation: ${employee.designation}`,
            `Document type: ${entry.category}`,
            `Issued: ${addDays(employee.dateOfJoining, -intBetween(30, 900)).toDateString()}`,
        ]);
        documentRows.push({
            employee: employee._id,
            category: entry.category,
            name: entry.name,
            originalName: `${entry.name.replace(/\s+/g, '-').toLowerCase()}.pdf`,
            filePath: relativePath,
            fileType: 'application/pdf',
            fileSize: size,
            issueDate: addDays(employee.dateOfJoining, -intBetween(30, 900)),
            expiryDate: chance(0.3) ? addDays(NOW, intBetween(10, 400)) : undefined,
            isVerified: status === 'VERIFIED',
            status,
            rejectionReason: status === 'REJECTED' ? 'Scan is not legible — please re-upload a clearer copy.' : undefined,
            verifiedBy: status === 'PENDING' ? undefined : superAdmin._id,
            verifiedAt: status === 'PENDING' ? undefined : addDays(employee.dateOfJoining, 5),
            isArchived: false,
            uploadedBy: superAdmin._id,
            createdAt: addDays(employee.dateOfJoining, -intBetween(1, 20)),
        });
    }

    for (let i = 0; i < documentEmployees.length; i += 1) {
        const employee = documentEmployees[i];
        if (i === 0) {
            // Showcase: fully documented — every required category, all VERIFIED.
            for (const category of requiredCategories) await seedDocument(employee, catalogueByCategory[category], 'VERIFIED');
        } else if (i === 1) {
            // Showcase: one required document REJECTED, the rest VERIFIED.
            for (const category of requiredCategories) {
                await seedDocument(employee, catalogueByCategory[category], category === 'Aadhaar Card' ? 'REJECTED' : 'VERIFIED');
            }
        } else if (i === 2) {
            // Showcase: fully documented but one required category still under review.
            for (const category of requiredCategories) {
                await seedDocument(employee, catalogueByCategory[category], category === 'PAN Card' ? 'PENDING' : 'VERIFIED');
            }
        } else {
            // Everyone else: a realistic, partial, randomised spread —
            // demonstrates MISSING categories alongside the other statuses.
            const catalogue = data.documentCatalogue.slice(0, intBetween(3, 7));
            for (const entry of catalogue) {
                const roll = rnd();
                const status = roll < 0.55 ? 'VERIFIED' : roll < 0.85 ? 'PENDING' : 'REJECTED';
                await seedDocument(employee, entry, status);
            }
        }
    }
    await EmployeeDocument.insertMany(documentRows);
    console.log(`✅ ${documentRows.length} documents (PDFs written under ${UPLOAD_DIR}/documents)`);

    // Persist each employee's documentStatus/hasRejectedDocuments from the
    // documents just seeded, exactly as documentController.syncDocumentStatus
    // would compute it live — so the HR list and dashboards are correct from
    // the very first page load, not just after someone opens the checklist.
    const rowsByEmployee = new Map();
    for (const row of documentRows) {
        const key = String(row.employee);
        if (!rowsByEmployee.has(key)) rowsByEmployee.set(key, []);
        rowsByEmployee.get(key).push(row);
    }
    let documentedCount = 0;
    for (const employee of employees) {
        const rows = rowsByEmployee.get(String(employee._id)) || [];
        const checklist = buildChecklist(employee, rows);
        employee.documentStatus = checklist.summary.isComplete ? 'COMPLETE' : 'PENDING';
        employee.hasRejectedDocuments = hasRejectedRequiredDocument(checklist);
        if (rows.length) documentedCount += 1;
        await employee.save();
    }
    console.log(`✅ document-completion status synced for ${documentedCount} documented employee(s)`);

    // Identity documents — numbers are stored encrypted, displayed masked.
    let identityCount = 0;
    if (process.env.ENCRYPTION_KEY) {
        const identityRows = [];
        for (const employee of documentEmployees.slice(0, 12)) {
            const aadhaar = `${intBetween(2000, 9999)}${intBetween(1000, 9999)}${intBetween(1000, 9999)}`;
            const pan = `ABCDE${intBetween(1000, 9999)}F`;
            identityRows.push(
                { employee: employee._id, documentType: 'AADHAAR', encryptedNumber: encrypt(aadhaar), maskedNumber: maskIdentityNumber('AADHAAR', aadhaar), isVerified: true },
                { employee: employee._id, documentType: 'PAN', encryptedNumber: encrypt(pan), maskedNumber: maskIdentityNumber('PAN', pan), isVerified: true },
            );
        }
        await IdentityDocument.insertMany(identityRows);
        identityCount = identityRows.length;
    } else {
        console.warn('⚠️  ENCRYPTION_KEY is not set — skipping identity documents');
    }
    console.log(`✅ ${identityCount} identity documents`);

    // -----------------------------------------------------------------------
    // Policies + acknowledgements
    // -----------------------------------------------------------------------
    const savedPolicies = await Policy.insertMany(data.policies.map((p, i) => ({
        ...p,
        publishedAt: p.status === 'PUBLISHED' ? addDays(NOW, -(30 + i * 12)) : undefined,
        publishedBy: p.status === 'PUBLISHED' ? superAdmin._id : undefined,
        createdBy: superAdmin._id,
    })));
    const ackRows = [];
    for (const policy of savedPolicies.filter((p) => p.status === 'PUBLISHED' && p.isAcknowledgementRequired)) {
        for (const employee of activeEmployees) {
            if (!chance(0.65)) continue;
            ackRows.push({
                policy: policy._id,
                employee: employee._id,
                acknowledgedAt: addDays(policy.publishedAt, intBetween(1, 20)),
                version: policy.version,
            });
        }
    }
    await PolicyAcknowledgement.insertMany(ackRows);
    console.log(`✅ ${savedPolicies.length} policies, ${ackRows.length} acknowledgements`);

    // -----------------------------------------------------------------------
    // Announcements + read receipts
    // -----------------------------------------------------------------------
    const savedAnnouncements = await Announcement.insertMany(data.announcements.map((a) => ({
        title: a.title,
        description: a.description,
        priority: a.priority,
        targetAudience: a.targetAudience,
        targetDepartments: a.targetDepartments || [],
        targetDesignations: [],
        targetEmployees: [],
        publishDate: addDays(NOW, -a.daysAgo),
        isActive: true,
        createdBy: superAdmin._id,
        createdAt: addDays(NOW, -a.daysAgo),
    })));
    const readRows = [];
    for (const announcement of savedAnnouncements) {
        for (const employee of activeEmployees) {
            if (!chance(0.55)) continue;
            readRows.push({ announcement: announcement._id, employee: employee._id, readAt: addDays(announcement.publishDate, 1) });
        }
    }
    await AnnouncementRead.insertMany(readRows);
    console.log(`✅ ${savedAnnouncements.length} announcements, ${readRows.length} read receipts`);

    // -----------------------------------------------------------------------
    // Assets + assignment history
    // -----------------------------------------------------------------------
    const assetRows = [];
    let assetSeq = 1;
    for (const item of data.assetCatalogue) {
        const copies = intBetween(2, 4);
        for (let i = 0; i < copies; i += 1) {
            assetRows.push({
                assetCode: `DL-AST-${String(assetSeq++).padStart(4, '0')}`,
                name: item.name,
                type: item.type,
                brand: item.brand,
                model: item.model,
                serialNumber: `SN${intBetween(100000, 999999)}${String.fromCharCode(65 + intBetween(0, 25))}`,
                purchaseDate: addDays(NOW, -intBetween(60, 900)),
                purchaseValue: item.value,
                condition: pick(['NEW', 'GOOD', 'GOOD', 'FAIR']),
                status: 'AVAILABLE',
                location: pick(['Bengaluru HQ — Floor 3', 'Bengaluru HQ — Floor 4', 'Hyderabad Office', 'Store room']),
                isActive: true,
                createdBy: superAdmin._id,
            });
        }
    }
    const savedAssets = await Asset.insertMany(assetRows);

    // Assign a laptop and a peripheral to most active employees.
    const assignments = [];
    const pool = {
        Laptop: savedAssets.filter((a) => a.type === 'Laptop'),
        Peripheral: savedAssets.filter((a) => a.type === 'Peripheral'),
        Monitor: savedAssets.filter((a) => a.type === 'Monitor'),
    };
    const cursors = { Laptop: 0, Peripheral: 0, Monitor: 0 };
    for (const employee of activeEmployees) {
        for (const type of ['Laptop', 'Monitor', 'Peripheral']) {
            if (type !== 'Laptop' && !chance(0.5)) continue;
            const asset = pool[type][cursors[type]];
            if (!asset) continue;
            cursors[type] += 1;
            const assignedAt = addDays(employee.dateOfJoining, intBetween(0, 3));
            asset.status = 'ASSIGNED';
            asset.assignedTo = employee._id;
            asset.assignedAt = assignedAt;
            await asset.save();
            assignments.push({
                asset: asset._id,
                employee: employee._id,
                assignedAt,
                conditionAtAssignment: asset.condition,
                notes: 'Issued as part of onboarding.',
                assignedBy: superAdmin._id,
            });
        }
    }
    // A handful of closed assignments so the history view has returns in it.
    const returnable = savedAssets.filter((a) => a.status === 'AVAILABLE').slice(0, 6);
    for (const asset of returnable) {
        const employee = pick(activeEmployees);
        const assignedAt = addDays(NOW, -intBetween(200, 400));
        assignments.push({
            asset: asset._id,
            employee: employee._id,
            assignedAt,
            returnedAt: addDays(assignedAt, intBetween(60, 150)),
            conditionAtAssignment: 'NEW',
            conditionAtReturn: pick(['GOOD', 'FAIR']),
            notes: 'Returned on role change.',
            assignedBy: superAdmin._id,
            returnedBy: superAdmin._id,
        });
    }
    // Two units under maintenance so the status filter has something to show.
    for (const asset of savedAssets.filter((a) => a.status === 'AVAILABLE').slice(6, 9)) {
        asset.status = 'MAINTENANCE';
        asset.condition = 'DAMAGED';
        asset.notes = 'Sent to the service centre for repair.';
        await asset.save();
    }
    await AssetAssignment.insertMany(assignments);
    console.log(`✅ ${savedAssets.length} assets, ${assignments.length} assignment records`);

    // -----------------------------------------------------------------------
    // Onboarding / offboarding tasks
    // -----------------------------------------------------------------------
    const onboardingRows = [];
    const recentJoiners = activeEmployees
        .filter((e) => addDays(e.dateOfJoining, 180) >= NOW)
        .slice(0, 14);
    for (const employee of recentJoiners) {
        const progressed = rnd();
        TEMPLATES.onboarding.forEach((task, index) => {
            const ratio = (index + 1) / TEMPLATES.onboarding.length;
            let status = 'TODO';
            if (ratio <= progressed) status = 'COMPLETED';
            else if (ratio <= progressed + 0.15) status = 'IN_PROGRESS';
            else if (chance(0.06)) status = 'BLOCKED';
            onboardingRows.push({
                employee: employee._id,
                taskName: task.taskName,
                description: task.description,
                category: task.category,
                dueDate: addDays(employee.dateOfJoining, task.offsetDays),
                status,
                completedAt: status === 'COMPLETED' ? addDays(employee.dateOfJoining, task.offsetDays) : undefined,
                completedBy: status === 'COMPLETED' ? superAdmin._id : undefined,
                assignedTo: superAdmin._id,
                isRequired: true,
                order: index,
            });
        });
    }
    await OnboardingTask.insertMany(onboardingRows);

    const offboardingRows = [];
    const leavers = employees.filter((e) => e.dateOfExit);
    for (const employee of leavers) {
        const progressed = employee.status === 'INACTIVE' ? 1 : rnd() * 0.8;
        TEMPLATES.offboarding.forEach((task, index) => {
            const ratio = (index + 1) / TEMPLATES.offboarding.length;
            let status = 'TODO';
            if (ratio <= progressed) status = 'COMPLETED';
            else if (ratio <= progressed + 0.2) status = 'IN_PROGRESS';
            offboardingRows.push({
                employee: employee._id,
                taskName: task.taskName,
                description: task.description,
                category: task.category,
                dueDate: addDays(employee.dateOfExit, task.offsetDays),
                status,
                completedAt: status === 'COMPLETED' ? addDays(employee.dateOfExit, task.offsetDays) : undefined,
                completedBy: status === 'COMPLETED' ? superAdmin._id : undefined,
                assignedTo: superAdmin._id,
                isRequired: true,
                order: index,
            });
        });
    }
    await OffboardingTask.insertMany(offboardingRows);
    console.log(`✅ ${onboardingRows.length} onboarding tasks, ${offboardingRows.length} offboarding tasks`);

    // -----------------------------------------------------------------------
    // Notifications
    // -----------------------------------------------------------------------
    const notificationRows = [];
    for (const employee of activeEmployees) {
        if (!employee.user) continue;
        const latest = savedAnnouncements[0];
        notificationRows.push({
            user: employee.user,
            type: 'ANNOUNCEMENT',
            title: latest.title,
            message: latest.description.slice(0, 140),
            isRead: chance(0.4),
            relatedModel: 'Announcement',
            relatedId: latest._id,
            createdAt: latest.publishDate,
        });
        const payslip = payslipRows.find((p) => String(p.employee) === String(employee._id));
        if (payslip) {
            notificationRows.push({
                user: employee.user,
                type: 'PAYSLIP_GENERATED',
                title: 'Payslip available',
                message: `Your payslip for ${payslip.month}/${payslip.year} is ready to download.`,
                isRead: chance(0.5),
                relatedModel: 'Payslip',
                relatedId: payslip._id,
                createdAt: addDays(NOW, -intBetween(2, 25)),
            });
        }
        const pendingLeave = accepted.find((r) => String(r.employee) === String(employee._id) && r.status === 'APPROVED');
        if (pendingLeave) {
            notificationRows.push({
                user: employee.user,
                type: 'LEAVE_APPROVED',
                title: 'Leave approved',
                message: `Your leave from ${new Date(pendingLeave.startDate).toLocaleDateString('en-IN')} was approved.`,
                isRead: chance(0.6),
                relatedModel: 'LeaveRequest',
                relatedId: undefined,
                createdAt: pendingLeave.approvedAt || NOW,
            });
        }
    }
    await Notification.insertMany(notificationRows);
    console.log(`✅ ${notificationRows.length} notifications`);

    // -----------------------------------------------------------------------
    // Audit trail
    // -----------------------------------------------------------------------
    const auditRows = [];
    const auditActors = [
        { userId: superAdmin._id, userEmail: 'admin@launcherdesk.com' },
        { userId: roleUsers.find((u) => u.role === 'HR_ADMIN')._id, userEmail: 'hr@launcherdesk.com' },
        { userId: roleUsers.find((u) => u.role === 'FINANCE')._id, userEmail: 'finance@launcherdesk.com' },
    ];
    employees.slice(0, 25).forEach((employee, i) => {
        const actor = auditActors[i % auditActors.length];
        auditRows.push({
            ...actor,
            action: 'EMPLOYEE_CREATED', module: 'EMPLOYEES',
            recordId: String(employee._id), recordLabel: employee.fullName,
            newValue: { employeeCode: employee.employeeCode, department: employee.department },
            ipAddress: `10.0.${intBetween(0, 5)}.${intBetween(2, 250)}`,
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
            createdAt: addDays(employee.dateOfJoining, -1),
        });
    });
    const auditTemplates = [
        { action: 'LOGIN', module: 'AUTH' },
        { action: 'LEAVE_APPROVED', module: 'LEAVE' },
        { action: 'PAYSLIP_GENERATED', module: 'PAYROLL' },
        { action: 'DOCUMENT_VERIFIED', module: 'DOCUMENTS' },
        { action: 'ASSET_ASSIGNED', module: 'ASSETS' },
        { action: 'POLICY_PUBLISHED', module: 'POLICIES' },
        { action: 'ATTENDANCE_EDITED', module: 'ATTENDANCE' },
        { action: 'ANNOUNCEMENT_CREATED', module: 'ANNOUNCEMENTS' },
        { action: 'IDENTITY_REVEALED', module: 'IDENTITY' },
        { action: 'ONBOARDING_TASK_UPDATED', module: 'ONBOARDING' },
        { action: 'COMPENSATION_REQUESTED', module: 'PAYROLL' },
        { action: 'COMPENSATION_APPROVED', module: 'PAYROLL' },
    ];
    for (let i = 0; i < 160; i += 1) {
        const template = pick(auditTemplates);
        const actor = pick(auditActors);
        const subject = pick(employees);
        auditRows.push({
            ...actor,
            action: template.action,
            module: template.module,
            recordId: String(subject._id),
            recordLabel: subject.fullName,
            ipAddress: `10.0.${intBetween(0, 5)}.${intBetween(2, 250)}`,
            userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
            createdAt: addDays(NOW, -intBetween(0, 60)),
        });
    }
    await AuditLog.insertMany(auditRows);
    console.log(`✅ ${auditRows.length} audit log entries`);

    // -----------------------------------------------------------------------
    console.log('\n' + '='.repeat(58));
    console.log('SEED COMPLETE — test accounts (development only)');
    console.log('='.repeat(58));
    console.log(`SUPER_ADMIN : admin@launcherdesk.com     / ${ADMIN_PASSWORD}`);
    console.log(`HR_ADMIN    : hr@launcherdesk.com        / ${ADMIN_PASSWORD}`);
    console.log(`FINANCE     : finance@launcherdesk.com   / ${ADMIN_PASSWORD}`);
    console.log(`AUDITOR     : auditor@launcherdesk.com   / ${ADMIN_PASSWORD}`);
    console.log('-'.repeat(58));
    console.log('Employee logins (all use the same password below):');
    console.log(`FOUNDER_CEO : moqsood@launcherdesk.com   / ${EMPLOYEE_PASSWORD}`);
    console.log(`CTO         : bhojraj@launcherdesk.com   / ${EMPLOYEE_PASSWORD}  (FOUNDER_CEO-equivalent)`);
    console.log(`DIRECTOR    : ameena@launcherdesk.com    / ${EMPLOYEE_PASSWORD}  (read-only)`);
    console.log(`FINANCE     : meera.krishnan@launcherdesk.com / ${EMPLOYEE_PASSWORD}`);
    console.log(`PROJECT_HEAD: srinivas@launcherdesk.com  / ${EMPLOYEE_PASSWORD}  (self + direct reports only)`);
    console.log(`EMPLOYEE    : jeevan@launcherdesk.com    / ${EMPLOYEE_PASSWORD}`);
    console.log(`AUDITOR     : aditya.saxena@launcherdesk.com / ${EMPLOYEE_PASSWORD}`);
    console.log('='.repeat(58));

    await mongoose_1.default.disconnect();
}

seed()
    .then(() => process.exit(0))
    .catch((err) => {
        console.error('❌ Seed failed:', err);
        process.exit(1);
    });
